name: CI-CD-to-AWS
# прописываю env
env:
  envirement_name: "react-app-env"
  deploy_package_name: "react_app_${{ github.sha }}"
  aws_region_name: "eu-north-1"
# Запустить PUSH и PULL запрос для главнй ветки (при изменении главной ветки будет запускатся)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 # установка нужной версии nodejs       
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.4 
 # установка npm
      - name: Use npm
        run : npm install
      - run : npm --version
      - run : yarn start  
      - run : yarn test
      - run : yarn build

