name: CI-CD
# Запустить PUSH и PULL запрос для главнй ветки (при изменении главной ветки будет запускатся)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js # ставлю нужную версию Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    
    - name: Setup key
      run : set -eu
    - run : mkdir "$HOME/.ssh"
    - run : echo "${{ secrets.SERVER_KEY }}" > "$HOME/.ssh/key"
    - run : chmod 600 "$HOME/.ssh/key"
    
    - name: Install npm dependencies 
      run : npm install
    - name: Run build task
      run : npm run build --if-present     
      
    - name: Deploy to Server
      run : rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyCheking=no" --archive --compress --delete .root@devops-test-ubuntu-1vcpu-2gb-fra1-01:/var/www/html/site/
