name: CI-CD
# Запустить PUSH запрос для главнй ветки (при изменении главной ветки будет запускатся)
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js # ставлю нужную версию Nodejs npm тоже станет
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    - run : npm install -g yarn # последняя глобальная версия yarn
    
    - name: Setup key # перемещаю ключ для доступа на сервер
      run : set -eu
    - run : mkdir "$HOME/.ssh"
    - run : echo "${{ secrets.SERVER_KEY }}" > "$HOME/.ssh/key"
    - run : chmod 600 "$HOME/.ssh/key" # доступ к ключу
    
    - name: Install npm dependencies 
      run : npm install # Установка всех зависимостей, перечисленных в package.json
    - run : yarn start # Запускает приложение в режиме разработки. http://localhost:3000
    - run : yarn test -- --watchAll=false # запуска тестов в неинтерактивном режиме
    - run : yarn build # Создает приложение для производства в build папке
      
    - name: Deploy to Server # отправка на сервер
      uses: easingthemes/ssh-deploy@v2.1.5
      env :
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }} # ключ
          REMOTE_HOST    : ${{ secrets.IP_SERVER }} # домен или ip
          REMOTE_USER    : ${{ secrets.USER_SERVER_NAME }} # имя пользователя(root или другое)
          TARGET         : "/var/www/html/site/" # нужная директория на сервере

