name: CI-CD
# Запустить PUSH и PULL запрос для главнй ветки (при изменении главной ветки будет запускатся)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js # ставлю нужную версию Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    - name: Install npm dependencies 
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.IP_SERVER }}
          REMOTE_USER: ${{ secrets.USER_SERVER_NAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

